# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: CI

on:
  ## 触发条件, release.json有被修改
  push:
    paths:
      # Trigger only when src/** changes
      - ".github/release.json"
      
  pull_request:
    paths:
    # Trigger only when src/** changes
      - ".github/release.json"

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    ## 取出项目代码，设置java环境
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project
    
    ## 从release.json 读取相关信息
    - name: Read tag_main
      id: tag_main
      uses:  ashley-taylor/read-json-property-action@v1.0
      with:
        path: ./.github/release.json
        property: tag_main
    
    - name: Read tag_latest
      id: tag_latest
      uses:  ashley-taylor/read-json-property-action@v1.0
      with:
        path: ./.github/release.json
        property: tag_latest
    
    - name: Read download_url
      id: download_url
      uses:  ashley-taylor/read-json-property-action@v1.0     
      with:
      path: ./.github/release.json 
      property: download_url
      
    - name: Read file_name
      id: file_name
      uses:  ashley-taylor/read-json-property-action@v1.0     
      with:
      path: ./.github/release.json 
      property: file_name
      
        
    - name: Read description
      id: description
      uses: juliangruber/read-file-action@v1
      with:
      path: ./.github/release.info
      
      # Runs a set of commands using the runners shell

